#!/bin/sh

set -eux

poetry run ansible-galaxy role install -r ansible/requirements.yml --force
poetry run ansible-playbook ansible/playbooks/*.yml --syntax-check
poetry run ansible-lint -p ansible/playbooks/*.yml ansible/roles/github_cli ansible/roles/rust ansible/roles/i3 ansible/roles/markdown_mimetype
