#!/bin/sh

all_executable_files=$(find . -executable -type f -and -not -path "./.git*" -printf "%p ")

set -x

bash -O extglob -O globstar -O nullglob -c "shellcheck **/!(git-prompt).sh $all_executable_files -e SC1071"
