#!/bin/sh

all_executable_files=$(find . -executable -type f -and -not -path "./.git*" -and -not -path "./zsh/.zsh/*" -and -not -path "./zsh-autosuggestions/*" -printf "%p ")
set -x

bash -O extglob -O globstar -O nullglob -c "shellcheck $all_executable_files -e SC1071 -x"
