sudo: required

language: generic

services:
  - docker

env:
  - USER=root

install:
  - docker build -t dotfiles .
  - docker run dotfiles test/shellcheck
  - docker run dotfiles ./setup -a && test/ansible && test/i3

script:
  - docker ps | grep -q dotfiles

