---
sudo: required

language: python

cache: pip

python:
  - 3.6

env:
  global:
    - USER=root

branches:
  only:
    master

jobs:
  include:
    - stage: test
      name: Molecule role part 1
      install: |
        pip3 install virtualenv
        virtualenv virtenv
        source virtenv/bin/activate

        pip install molecule docker ansible
      script: |
        source virtenv/bin/activate

        cd ansible/roles/markdown_mimetype && molecule test && cd -
        cd ansible/roles/i3 && molecule test && cd -
        cd ansible/roles/rust && molecule test && cd -
    - stage: test
      name: Molecule role part 2
      install: |
        pip3 install virtualenv
        virtualenv virtenv
        source virtenv/bin/activate

        pip install molecule docker ansible
      script: |
        source virtenv/bin/activate

        cd ansible/roles/ripgrep && molecule test && cd -
        cd ansible/roles/github_hub && molecule test && cd -
        cd ansible/roles/spotify && molecule test && cd -
    - stage: test
      name: Basic lints
      install:
        - docker build -t dotfiles .
      script:
        - docker run dotfiles /bin/bash -c "./setup"
        - docker run dotfiles test/vim
        - docker run dotfiles test/yaml
        - docker run dotfiles test/shellcheck
    - stage: test
      name: Full setup test
      install:
        - docker build -t dotfiles .
      script:
        - docker run dotfiles /bin/bash -c "./setup -a; ./test/ansible; ./test/i3"
