---
sudo: required

language: generic

services:
  - docker

env:
  global:
    - USER=root

branches:
  only:
    master

install:
  - pip install molecule
  - pip install "molecule[docker]"
  - docker build -t dotfiles .

script:
  - docker run dotfiles test/vim
  - docker run dotfiles test/yaml
  - docker run dotfiles test/shellcheck
  - cd ansible/roles/ripgrep && molecule test
  - docker run dotfiles /bin/bash -c "./setup -a; ./test/ansible; ./test/i3"
