---
extends: default


ignore: |
  ansible/roles/geerlingguy.docker/
  ansible/roles/angstwad.docker_ubuntu/
  ansible/roles/FGtatsuro.python-requirements/
  ansible/roles/FGtatsuro.virtualbox/
  ansible/roles/FGtatsuro.vagrant/
  .venv/

rules:
  line-length:
    max: 120
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error

  truthy: disable
