---
extends: default


ignore: |
  ansible/roles/geerlingguy.docker/
  ansible/roles/FGtatsuro.python-requirements/
  ansible/roles/FGtatsuro.virtualbox/
  ansible/roles/FGtatsuro.vagrant/
  .venv/

rules:
  line-length:
    max: 120

  truthy: disable
