#!/usr/bin/env bash

do_setup() {
  bootstrap "$1"
  ssh_save
  finish
}

bootstrap()
{
  print_message "[setup] Ensure add-apt-repository is installed"
  run_with_sudo apt-get update -qq
  run_with_sudo apt-get install software-properties-common -qq
  print_message "[setup] Adding ansible ppa..."
  run_with_sudo add-apt-repository ppa:ansible/ansible -y > /dev/null

  print_message "[setup] Upgrading and autocleaning packages..."
  run_with_sudo apt-get update -qq
  run_with_sudo apt-get upgrade -qq --force-yes
  run_with_sudo apt-get autoremove -y -qq

  print_message "[setup] Installing Ansible and git..."
  run_with_sudo apt-get install -qq git ansible

  if [ -d "$HOME/.dotfiles" ]; then
    print_message "[setup] Updating dotfiles..."
    cd "$HOME/.dotfiles" && git checkout master -q && git pull -q
  else
    print_message "[setup] Cloning dotfiles..."
    git clone -q https://gitlab.com/phansch/dotfiles.git "$HOME/.dotfiles" && cd "$HOME/.dotfiles" || exit
  fi

  default_playbooks=(
    ansible/playbooks/base.yml
    ansible/playbooks/dotfiles.yml
  )
  print_message "[setup] Running default playbooks..."
  ansible-playbook "${default_playbooks[@]}" --ask-become-pass -u "$USER"

  additional_playbooks=(
    ansible/playbooks/rvm_tmuxinator.yml
    ansible/playbooks/spotify.yml
    ansible/playbooks/additional_packages.yml
    ansible/playbooks/i3.yml
    ansible/playbooks/qutebrowser.yml
    ansible/playbooks/udev.yml
  )

  cmd="ansible-playbook ${additional_playbooks[*]} --ask-become-pass -u $USER"
  if [ "$1" = true ] ; then
    print_message "[setup] Running all additional playbooks"
    run_with_sudo ansible-galaxy install -r ansible/requirements.yml --force
    ansible-playbook "${additional_playbooks[@]}" --ask-become-pass -u "$USER"
  else
    print_message "[setup] To run the rest of the playbooks:"
    print_message "$cmd"
  fi

}

ssh_save()
{

  if [[ -n "$CI" ]]; then return; fi
  ask_for_confirmation "[setup] Do you want to add your ssh key to ssh-agent? "
  if answer_is_yes; then
    ssh-add "$HOME/.ssh/id_rsa" &>/dev/null
  fi
}

finish()
{
  if [[ -n "$CI" ]]; then return; fi
  ask_for_confirmation "[setup] Almost done. Do you want to re-login now to complete the setup? "
  if answer_is_yes; then
    xfce4-session-logout --logout
  else
    exit
  fi
}

answer_is_yes() {
  [[ "$REPLY" =~ ^[Yy]$ ]] \
    && return 0 \
    || return 1
}

ask_for_confirmation() {
  printf "%b" "$1 (y/n)"
  read -r -n 1
  printf "%b" "\n"
}

print_message() {
  printf "%b" "$1\n"
}

# This is a wrapper around sudo for gitlab-ci
# Because gitlab-ci runners don't seem to have sudo and are root already.
run_with_sudo() {
  my_sudo=""

  if [[ $(id -u) -ne 0 ]] ; then
    print_message "We are not root, using 'sudo'"
    my_sudo='sudo'
  fi

  $my_sudo "$@"
}

while getopts "a" opt; do
  case "$opt" in
    a)
      all=true
      ;;
    \?)
      echo >&2 \
        "usage: $0 [-a]"
      exit 1;;
  esac
done
shift $((OPTIND-1))

do_setup "$all"
