---
- name: Install curl
  apt:
    pkg:
      - curl
- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y  # noqa 303 301 306
  changed_when: false
  args:
    warn: false
