---
- name: Install curl
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - curl
      - libssl-dev
      - libsensors-dev
- name: Install rustup
  # noqa no-changed-when command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
  changed_when: false

- name: Install extra cargo packages
  ansible.builtin.shell: ~/.cargo/bin/cargo install {{ item }} # noqa no-changed-when command-instead-of-shell
  loop: "{{ rust_extra_cargo_packages }}"
  changed_when: false
