---
- name: Prepare
  hosts: all
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - libdbus-glib-1-dev
          - libssl-dev
        state: present
        update_cache: true

- name: Converge
  hosts: all
  roles:
    - role: rust
      vars:
        rust_extra_cargo_packages: []
