---
- name: Prepare
  hosts: all
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - libdbus-glib-1-dev
          - libssl-dev
        state: present

- name: Converge
  hosts: all
  roles:
    - role: rust
      vars:
        extra_cargo_packages: []
