---
- name: Install gpg
  apt:
    pkg:
      - gpg
- name: Add apt-key
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    state: present
- name: Add spotify source
  apt_repository: repo="deb http://repository.spotify.com stable non-free"
  become: true
- name: Install spotify-client
  apt: update_cache=yes name=spotify-client
