---
- name: Install curl and JQ
  ansible.builtin.apt:
    pkg:
      - curl
      - jq
    state: present
    update_cache: true
- name: Get latest release URL
  shell: |
    curl -s https://api.github.com/repos/cli/cli/releases/latest \
    | jq -r '.assets[] | select(.name | test("{{ github_cli_file }}")) | .browser_download_url'
  args:
    executable: /bin/bash
  retries: 3 # Sometimes the JSON contains just `null` instead of the URL
  delay: 2
  register: download_url
  until: download_url.rc == 0
  changed_when: false
  tags:
    - skip_ansible_lint
- name: Cleanup existing
  ansible.builtin.file:
    path: /tmp/gh_cli.deb
    state: absent
  changed_when: false
- name: Download latest release
  ansible.builtin.get_url:
    url: "{{ download_url.stdout }}"
    # We remove the file at the end, so permissions shouldn't matter
    dest: /tmp/gh_cli.deb # noqa risky-file-permissions
  changed_when: false
- name: Install latest release
  ansible.builtin.apt:
    deb: /tmp/gh_cli.deb
- name: Remove tmp file
  ansible.builtin.file:
    path: /tmp/gh_cli.deb
    state: absent
  changed_when: false
