---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Install additional apt packages
    action: apt pkg={{ item }} state=present update_cache=yes
    with_items:
      - unclutter
      - shutter
      - libreoffice-calc
      - deja-dup
      - jq
      - redshift
      - ctags
  - name: Create tmp download dir
    file: path=/tmp/ansible-debs state=directory
  - name: Install additional deb packages
    apt: deb={{ item }} state=present
    with_items:
      - https://go.skype.com/skypeforlinux-64.deb
  - name: Add neovim repository
    shell: add-apt-repository -y ppa:neovim-ppa/unstable
  - name: Install python3-pip
    apt: name=python3-pip
  - name: Install python packages for neovim
    pip:
      name: neovim
      executable: pip3
  - name: Install neovim
    apt: name=neovim update_cache=yes
  - name: Set nvim as vi alternative
    shell: update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
  - name: Set nvim as vim alternative
    shell: update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
  - name: Set nvim as editor alternative
    shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
  - name: Add keepassxc repository
    shell: add-apt-repository ppa:phoerious/keepassxc
  - name: Install keepassxc
    apt: name=keepassxc update_cache=yes
