---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Add virtualbox apt key
    apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state=present
  - name: Add virtualbox repository
    apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
      state=present
  - name: Install additional apt packages
    action: apt pkg={{ item }} state=present
    with_items:
      - unclutter
      - virtualbox-5.1
      - shutter
      - keepassx
      - vagrant
  - name: Create tmp download dir
    file: path=/tmp/ansible-debs state=directory
  - name: Download .deb packages
    action: get_url url={{ item }} dest=/tmp/ansible-debs/
    with_items:
      - http://ankisrs.net/download/mirror/anki-2.0.33.deb
      - http://download.skype.com/linux/skype-ubuntu-precise_4.3.0.37-1_i386.deb
  - name: Install additional .deb packages
    shell: dpkg -i /tmp/ansible-debs/{{ item }} && apt-get -f -y -qq install
    with_items:
      - anki*
      - skype*
  # Ansible does not support apt_repository on Linux Mint right now
  - name: Add neovim repository
    shell: add-apt-repository -y ppa:neovim-ppa/unstable
  - name: Install neovim
    apt: name=neovim update_cache=yes
  - name: Set nvim as vi alternative
    shell: update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
  - name: Set nvim as vim alternative
    shell: update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
  - name: Set nvim as editor alternative
    shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
