---
- hosts: localhost
  become: true
  become_method: sudo
  roles:
    # - role: i3
    - role: rust
      become: false
      vars:
        extra_cargo_packages:
          - "--git https://github.com/greshake/i3status-rust i3status-rs"
    - role: markdown_mimetype
    # - role: FGtatsuro.vagrant
    - role: geerlingguy.docker
  tasks:
    - name: Install additional apt packages
      apt:
        pkg:
          - unclutter
          - xfce4-screenshooter
          - jq
          - redshift
          - ctags
          - krita
          - clementine
        state: present
        update_cache: true
    - name: Remove shutter
      apt:
        pkg:
          - shutter
        state: absent
        update_cache: true

    - name: Create tmp download dir
      file: path=/tmp/ansible-debs state=directory
    - name: Install additional deb packages
      apt: deb={{ item }} state=present
      with_items:
        - https://go.skype.com/skypeforlinux-64.deb
    - name: Setup various ppa repositories
      shell: add-apt-repository -y {{ item }}
      with_items:
        - ppa:git-core/ppa
    - name: Install packages from ppas
      apt:
        pkg:
          - git
        update_cache: true
    - name: Anki Latest
      unarchive:
        src: https://github.com/ankitects/anki/releases/download/2.1.35/anki-2.1.35-linux-amd64.tar.bz2
        dest: /opt
        remote_src: yes
    - name: Rename extracted folder
      command: mv --no-clobber /opt/anki-2.1.35-linux-amd64 /opt/anki
    - name: Symlink moved anki executable
      file:
        src: /opt/anki/bin/anki
        dest: /usr/bin/anki
        state: link