---
- name: Additional Packages
  hosts: localhost
  become: true
  roles:
    # - role: i3
    - role: rust
      vars:
        rust_extra_cargo_packages: []
      become: false
    - role: markdown_mimetype
    - role: geerlingguy.docker
      when: lookup('env', 'CI') == 'false'
  tasks:
    - name: Install additional apt packages
      ansible.builtin.apt:
        pkg:
          - unclutter
          - xfce4-screenshooter
          - jq
          - redshift
          - krita
        state: present
        update_cache: true
    - name: Remove shutter
      ansible.builtin.apt:
        pkg:
          - shutter
        state: absent
        update_cache: true

    - name: Setup various ppa repositories
      ansible.builtin.command: add-apt-repository -y {{ item }}
      with_items:
        - ppa:git-core/ppa
      changed_when: false
    - name: Install packages from ppas
      ansible.builtin.apt:
        pkg:
          - git
        update_cache: true
    - name: Anki Latest
      ansible.builtin.unarchive:
        src: https://github.com/ankitects/anki/releases/download/2.1.35/anki-2.1.35-linux-amd64.tar.bz2
        dest: /opt
        remote_src: true
    - name: Rename extracted folder
      ansible.builtin.command: mv --no-clobber /opt/anki-2.1.35-linux-amd64 /opt/anki
      changed_when: false
    - name: Symlink moved anki executable
      ansible.builtin.file:
        src: /opt/anki/bin/anki
        dest: /usr/bin/anki
        state: link
