---
- hosts: localhost
  become: true
  become_method: sudo
  roles:
    - role: i3
    - role: rust
    - role: markdown_mimetype
    # - role: FGtatsuro.vagrant
    - role: angstwad.docker_ubuntu
  tasks:
    - name: Install additional apt packages
      apt:
        pkg:
          - unclutter
          - xfce4-screenshooter
          - jq
          - redshift
          - ctags
          - krita
        state: present
        update_cache: true
    - name: Remove shutter
      apt:
        pkg:
          - shutter
        state: absent
        update_cache: true

    - name: Create tmp download dir
      file: path=/tmp/ansible-debs state=directory
    - name: Install additional deb packages
      apt: deb={{ item }} state=present
      with_items:
        - https://go.skype.com/skypeforlinux-64.deb
    # - name: Setup various ppa repositories
    #   shell: add-apt-repository -y {{ item }}
    #   with_items:
    #     - ppa:foo
    # - name: Install packages from ppas
    #   apt:
    #     pkg:
    #       - firefox-trunk
    #     update_cache: true
    - name: Install tmuxifier
      become: no
      git:
        repo: https://github.com/jimeh/tmuxifier.git
        dest: ~/.tmuxifier
