---
- hosts: localhost
  become: true
  become_method: sudo
  roles:
    - role: i3
    - role: rust
    - role: markdown_mimetype
    - role: FGtatsuro.vagrant
    - role: angstwad.docker_ubuntu
  tasks:
    - name: Install additional apt packages
      apt:
        pkg:
          - unclutter
          - shutter
          - libreoffice-calc
          - deja-dup
          - jq
          - redshift
          - ctags
          - newsbeuter
          - sqlitebrowser
        state: present
        update_cache: true
    - name: Create tmp download dir
      file: path=/tmp/ansible-debs state=directory
    - name: Install additional deb packages
      apt: deb={{ item }} state=present
      with_items:
        - https://go.skype.com/skypeforlinux-64.deb
    - name: Setup various ppa repositories
      shell: add-apt-repository -y {{ item }}
      with_items:
        - ppa:ubuntu-mozilla-daily/ppa
        - ppa:phoerious/keepassxc
    - name: Install packages from ppas
      apt:
        pkg:
          - firefox-trunk
          - keepassxc
        update_cache: true
    - name: Anki Latest
      unarchive:
        src: https://apps.ankiweb.net/downloads/current/anki-2.1.9-linux-amd64.tar.bz2
        dest: /opt
        remote_src: yes
    - name: Rename extracted folder
      command: mv --no-clobber /opt/anki-2.1.9-linux-amd64 /opt/anki
    - name: Symlink moved anki executable
      file:
        src: /opt/anki/bin/anki
        dest: /usr/bin/anki
        state: link
    - name: Install tmuxifier
      become: no
      git:
        repo: https://github.com/jimeh/tmuxifier.git
        dest: ~/.tmuxifier
