---
- name: Additional Packages
  hosts: localhost
  become: true
  roles:
    - role: i3
    - role: rust
      vars:
        rust_extra_cargo_packages: []
      become: false
    - role: markdown_mimetype
    - role: geerlingguy.docker
      when: lookup('env', 'CI') == 'false'
  tasks:
    - name: Install additional apt packages
      ansible.builtin.apt:
        pkg:
          - calibre
          - flatpak
          - unclutter
          - xfce4-screenshooter
          - jq
          - redshift
          - krita
          - flameshot
        state: present
        update_cache: true

    - name: Add flatpak flathub repository
      # yamllint disable-line rule:line-length
      ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      changed_when: false

    - name: Remove shutter
      ansible.builtin.apt:
        pkg:
          - shutter
        state: absent
        update_cache: true

    - name: Setup various ppa repositories
      ansible.builtin.command: add-apt-repository -y {{ item }}
      with_items:
        - ppa:git-core/ppa
      changed_when: false

    - name: Install packages from ppas
      ansible.builtin.apt:
        pkg:
          - git
        update_cache: true

    - name: Anki Latest
      ansible.builtin.unarchive:
        src: https://github.com/ankitects/anki/releases/download/2.1.35/anki-2.1.35-linux-amd64.tar.bz2
        dest: /opt
        remote_src: true

    - name: Rename extracted folder
      ansible.builtin.command: mv --no-clobber /opt/anki-2.1.35-linux-amd64 /opt/anki
      changed_when: false

    - name: Symlink moved anki executable
      ansible.builtin.file:
        src: /opt/anki/bin/anki
        dest: /usr/bin/anki
        state: link

    - name: Install Steam
      ansible.builtin.apt:
        deb: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
      tags:
        - games

    - name: Install Lutris
      community.general.flatpak:
        name: net.lutris.Lutris
        state: present
      tags:
        - games

    - name: Install Pika backup
      community.general.flatpak:
        name: org.gnome.World.PikaBackup
        state: present
