---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Install additional apt packages
    action: apt pkg={{ item }} state=present update_cache=yes
    with_items:
      - unclutter
      - shutter
      - libreoffice-calc
      - deja-dup
      - jq
      - redshift
      - ctags
      - newsbeuter
      - sqlitebrowser
  - name: Create tmp download dir
    file: path=/tmp/ansible-debs state=directory
  - name: Install additional deb packages
    apt: deb={{ item }} state=present
    with_items:
      - https://go.skype.com/skypeforlinux-64.deb
      - http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_17.10/amd64/purple-facebook_20180323~ef6ae47~9ff9acf9fa14~145_amd64.deb
  - name: Setup various ppa repositories
    shell: add-apt-repository -y {{ item }}
    with_items:
      - ppa:neovim-ppa/unstable
      - ppa:ubuntu-mozilla-daily/ppa
      - ppa:nextcloud-devs/client
      - ppa:phoerious/keepassxc
  - name: Install packages from ppas
    apt: name={{ item }} update_cache=yes
    with_items:
      - firefox-trunk
      - neovim
      - keepassxc
      - nextcloud-client
  - name: Install python3-pip
    apt: name=python3-pip
  - name: Install python packages for neovim
    pip:
      name: neovim
      executable: pip3
  - name: Install neovim
    apt: name=neovim update_cache=yes
  - name: Set nvim as vi alternative
    shell: update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
  - name: Set nvim as vim alternative
    shell: update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
  - name: Set nvim as editor alternative
    shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
  - set_fact:
      file_content: >
        <?xml version="1.0"?>
        <mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
          <mime-type type="text/plain">
            <glob pattern="*.md"/>
            <glob pattern="*.mkd"/>
            <glob pattern="*.markdown"/>
          </mime-type>
        </mime-info>
  - name: Prepare markdown mimetype directory
    become: no
    file:
      path: ~/.local/share/mime/packages/
      state: directory
      recurse: yes
  - name: Create new markdown mimetype file
    become: no
    file: path=~/.local/share/mime/packages/text-markdown.xml state=touch
  - name: Insert content into mimetype file
    become: no
    copy: content={{ file_content }} dest=~/.local/share/mime/packages/text-markdown.xml
  - name: Update mime database
    become: no
    shell: update-mime-database ~/.local/share/mime
  - name: Anki Latest Beta
    unarchive:
      src: https://apps.ankiweb.net/downloads/beta/anki-2.1.0rc1-linux-amd64.tar.bz2
      dest: /opt
      remote_src: yes
  - name: Rename extracted folder
    command: mv --no-clobber /opt/anki-2.1.0rc1-linux-amd64 /opt/anki
  - name: Symlink moved anki executable
    file:
      src: /opt/anki/bin/anki
      dest: /usr/bin/anki
      state: link
  - name: Install tmuxifier
    become: no
    git:
      repo: https://github.com/jimeh/tmuxifier.git
      dest: ~/.tmuxifier
