---
- hosts: localhost
  tasks:
    - name: Install borgbackup
      apt: pkg=borgbackup
    - name: Backup cron
      cron:
        name: Backup
        minute: "0"
        hour: "7"
        job: /home/phansch/.bin/backup 2>&1 | /usr/bin/logger -t backup_cron
        user: phansch
