---
- hosts: localhost
  tasks:
    - name: Install borgbackup
      become: true
      become_method: sudo
      apt:
        pkg:
          - cron
          - borgbackup
          - net-tools # needed for `arp` package
        state: present

    - name: Backup cron
      cron:
        name: Backup
        minute: "0"
        hour: "9"
        job: /home/{{ ansible_user_id }}/.bin/backup 2>&1 | /usr/bin/logger -t backup_cron
        user: "{{ ansible_user_id }}"
