---
- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - role: ripgrep
      vars:
        platform: amd64
        version: 0.10.0
    - role: github_hub
      vars:
        platform: linux-amd64
        dest_dir: ~/.bin/hub
  tasks:
    - name: Install base packages
      apt:
        pkg:
          - build-essential
          - cmake
          - libglib2.0-dev
          - xsel
          - xclip
          - xbindkeys
          - slock
          - zsh
          - arandr
          - rxvt-unicode-256color
          - tmux
          - git
          - feh
          - htop
          - fontconfig
          - curl
          - at
          - tree
          - pidgin
          - scrot
          - firejail
        state: present
    - name: Remove specific packages
      apt:
        pkg:
          - dc
          - xscreensaver
          - transmission-gtk
          - thunderbird
        state: absent
    - name: Set zsh as default shell
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh
        append: yes
    # Integrate git with libsecret
    - name: Install libsecret
      apt:
        pkg:
          - libsecret-1-0
          - libsecret-1-dev
        state: present
        update_cache: true
    - name: Check for libsecret Makefile
      stat: path=/usr/share/doc/git/contrib/credential/libsecret/Makefile
      register: makefile_present
    - name: Make libsecret git credential helper
      shell: make chdir=/usr/share/doc/git/contrib/credential/libsecret
      when: makefile_present.stat.exists
