---
- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - role: kagux.silversearcher_ag
  tasks:
    - name: Install base packages
      apt:
        pkg:
          - build-essential
          - cmake
          - libglib2.0-dev
          - xsel
          - xclip
          - xbindkeys
          - slock
          - zsh
          - arandr
          - rxvt-unicode-256color
          - tmux
          - git
          - feh
          - htop
          - fontconfig
          - curl
          - at
          - tree
          - pidgin
          - scrot
        state: present
    - name: Remove specific packages
      apt:
        pkg:
          - xscreensaver
          - transmission-gtk
          - thunderbird
        state: absent
    - name: Set zsh as default shell
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh
        append: yes
    # Fix gnome keyring
    - name: Install libgnome-keyring-dev
      apt: name=libgnome-keyring-dev
    - name: Make gnome-keyring git credential helper
      shell: make chdir=/usr/share/doc/git/contrib/credential/gnome-keyring
