---
- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - role: kagux.silversearcher_ag
  tasks:
    - name: Install base packages
      action: apt pkg={{ item }} state=present
      with_items:
        - build-essential
        - libglib2.0-dev
        - xsel
        - xbindkeys
        - slock
        - zsh
        - rxvt-unicode-256color
        - tmux
        - git
        - feh
        - htop
        - fontconfig
        - curl
    - name: Remove specific packages
      action: apt pkg={{ item }} state=absent
      with_items:
        - xscreensaver
    - name: Set zsh as default shell
      user: shell=/bin/zsh name={{ ansible_user_id }}
    # Fix gnome keyring
    - name: Install libgnome-keyring-dev
      apt: name=libgnome-keyring-dev
    - name: Make gnome-keyring git credential helper
      shell: make chdir=/usr/share/doc/git/contrib/credential/gnome-keyring
