---
- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - role: ripgrep
      vars:
        platform: amd64
        version: 0.10.0
    - role: github_cli
      vars:
        file: linux_amd64.deb
  tasks:
    - name: Add neovim ppa
      apt_repository:
        repo: 'ppa:neovim-ppa/unstable'
    - name: Install base packages
      apt:
        pkg:
          - build-essential
          - cmake
          - libglib2.0-dev
          - xsel
          - xclip
          - xbindkeys
          - slock
          - zsh
          - arandr
          - rxvt-unicode-256color
          - tmux
          - git
          - feh
          - htop
          - fontconfig
          - curl
          - at
          - tree
          - scrot
          - firejail
          - shellcheck
          - neovim
          - pulsemixer
          - mpd
          - ncmpcpp
          - fonts-noto-color-emoji
        state: present
    - name: Remove specific packages
      apt:
        pkg:
          - dc
          - xscreensaver
          - transmission-gtk
          - thunderbird
          - pidgin
        state: absent
    - name: Set zsh as default shell
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh
        append: yes
    - name: Set nvim as vi alternative
      shell: update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
    - name: Set nvim as vim alternative
      shell: update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
    - name: Set nvim as editor alternative
      shell: update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
    - name: Install python packages for neovim
      pip:
        name: neovim
        executable: pip3
    # Integrate git with libsecret
    - name: Install libsecret
      apt:
        pkg:
          - libsecret-1-0
          - libsecret-1-dev
        state: present
        update_cache: true
    - name: Check for libsecret Makefile
      stat: path=/usr/share/doc/git/contrib/credential/libsecret/Makefile
      register: makefile_present
    - name: Make libsecret git credential helper
      shell: make chdir=/usr/share/doc/git/contrib/credential/libsecret
      when: makefile_present.stat.exists
