---
- name: Base setup
  hosts: localhost
  become: true
  pre_tasks:
    - name: This playbook only runs on Ubuntu/Debian
      ansible.builtin.debug:
        msg: Aborting, this playbook only runs on Ubuntu/Debian
      when: ansible_os_family != 'Debian'
    - name: This playbook only runs on Ubuntu/Debian - end play
      ansible.builtin.meta: end_play
      when: ansible_os_family != 'Debian'
  roles:
    - role: github_cli
      vars:
        github_cli_file: linux_amd64.deb
  tasks:
    # Needed to skip snap installation in docker container
    - name: Get facts on current container, if any
      community.docker.current_container_facts:

    - name: Add ppas
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
      with_items:
        - ppa:aslatter/ppa
    - name: Install base APT packages
      ansible.builtin.apt:
        pkg:
          - autorandr
          - build-essential
          - cmake
          # - git-delete-merged-branches # Enable once the github actions are upgraded to Ubuntu 24
          - libglib2.0-dev
          - libssl-dev
          - lxappearance
          - xsel
          - xclip
          - xbindkeys
          - slock
          - zsh
          - arandr
          - tmux
          - git
          - feh
          - htop
          - fontconfig
          - curl
          - ripgrep
          - at
          - tree
          - scrot
          - firejail
          - shellcheck
          - pulsemixer
          - fonts-noto-color-emoji
          - rofi
          - xdg-utils
          - desktop-file-utils
          - snapd
          - unzip
        state: present

    - name: Remove specific APT packages
      ansible.builtin.apt:
        pkg:
          - dc
          - xscreensaver
          - transmission-gtk
          - thunderbird
          - pidgin
        state: absent

    - name: Install Snap packages
      community.general.snap:
        name:
          - code
          - obsidian
        classic: true
      when: not ansible_module_running_in_container

    - name: Set zsh as default shell
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh
        append: true

    - name: Setup zsh-autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: "{{ lookup('env', 'HOME') }}/.zsh/zsh-autosuggestions"
        update: false
        single_branch: yes
        version: v0.7.0
      changed_when: false
      tags: zsh

    - name: Create /opt/nvim dir
      ansible.builtin.file:
        path: /opt/nvim
        state: directory
        mode: '0755'

    - name: Install nvim via appimage
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
        dest: /opt/nvim/nvim
        mode: '0764'

    - name: Install python packages for neovim
      ansible.builtin.apt:
        pkg: python3-neovim

    # Integrate git with libsecret
    - name: Install libsecret
      ansible.builtin.apt:
        pkg:
          - libsecret-1-0
          - libsecret-1-dev
        state: present
        update_cache: true
    - name: Check for libsecret Makefile
      ansible.builtin.stat:
        path: /usr/share/doc/git/contrib/credential/libsecret/Makefile
      register: makefile_present

    - name: Make libsecret git credential helper
      ansible.builtin.command:
        cmd: make
        chdir: /usr/share/doc/git/contrib/credential/libsecret
      when: makefile_present.stat.exists
      changed_when: false # noqa no-changed-when

    - name: Install tmuxifier
      ansible.builtin.git:
        repo: https://github.com/jimeh/tmuxifier.git
        dest: "{{ lookup('env', 'HOME') }}/.tmuxifier"
        update: false
        version: "v0.13.0"
