---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Install python-pycurl for angstwad.docker_ubuntu
      apt: name=python-pycurl update_cache=yes

- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - role: angstwad.docker_ubuntu
