---
- hosts: localhost
  tasks:
    - name: Install gnu-stow
      become: yes
      apt: pkg=stow
    - name: Install dotfiles
      shell: stow {{ item }} --target=$HOME/ --dir=$HOME/.dotfiles
      with_items:
        - alacritty
        - autorandr
        - bin
        - fonts
        - git
        - gtk
        - gnupg
        - i3wm
        - notify
        - obsidian
        - redshift
        - ruby
        - tmux
        - vim
        - x
        - zsh
      changed_when: false
    - name: check for ~/.xinitrc
      stat: path=~/.xinitrc
      register: xinitrc_presence
    - name: fail if ~/.xinitrc not created
      fail: msg="~/.xinitrc was not created by stow"
      when: not xinitrc_presence.stat.exists

    # FIXME: move to ~/.local/share/fonts directory and figure out correct permissions
    - name: Create ~/.fonts directory
      file: path=~/.fonts state=directory  # noqa risky-file-permissions

    - name: Download Source Code Pro font
      # yamllint disable-line rule:line-length
      get_url: url=https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.ttf?raw=true
        dest=~/.fonts/
    - name: Refresh font cache
      command: fc-cache -f
      changed_when: false

    # Allow opening of obsidian:// URLs
    - name: Update application cache for obsidian URL handling
      command: update-desktop-database ~/.local/share/applications/
      changed_when: false
