---
- hosts: localhost
  tasks:
    - name: Install gnu-stow
      become: true
      ansible.builtin.apt:
        pkg: stow
        cmd: ""
    - name: Install dotfiles
      ansible.builtin.shell: stow {{ item }} --target=$HOME/ --dir=$HOME/.dotfiles
      with_items:
        - alacritty
        - autorandr
        - bin
        - fonts
        - git
        - gtk
        - gnupg
        - i3wm
        - notify
        - obsidian
        - redshift
        - ruby
        - tmux
        - vim
        - x
        - zsh
      changed_when: false
    - name: Check for ~/.xinitrc
      ansible.builtin.stat:
        path: ~/.xinitrc
        cmd: ""
      register: xinitrc_presence
    - name: Fail if ~/.xinitrc not created
      ansible.builtin.fail:
        msg: '"~/.xinitrc was not created by stow"'
      when: not xinitrc_presence.stat.exists

    # FIXME: move to ~/.local/share/fonts directory and figure out correct permissions
    - name: Create ~/.fonts directory
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        cmd: ""
    - name: Download Source Code Pro font
      # yamllint disable-line rule:line-length
      get_url: url=https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.ttf?raw=true
        dest=~/.fonts/
    - name: Refresh font cache
      ansible.builtin.command: fc-cache -f
      changed_when: false

    # Allow opening of obsidian:// URLs
    - name: Update application cache for obsidian URL handling
      ansible.builtin.command: update-desktop-database ~/.local/share/applications/
      changed_when: false
