---
- hosts: localhost
  tasks:
    - name: Install gnu-stow
      become: yes
      apt: pkg=stow
    - name: Install dotfiles
      shell: stow {{ item }} --target=$HOME/ --dir=$HOME/.dotfiles
      with_items:
        - bin
        - davfs2
        - fonts
        - git
        - gtk
        - i3wm
        - notify
        - redshift
        - ruby
        - screen
        - tmux
        - urxvt
        - vim
        - x
        - zsh
    - name: Install vim plugins
      shell: vim +'PlugInstall --sync' +qall &> /dev/null
    - name: Install vim-coc extensions
      shell: vim -c 'CocInstall -sync {{ item }}|q'
      with_items:
        - coc-solargraph
        - coc-rust-analyzer
        - coc-snippets
        - coc-eslint
    - name: check for ~/.xinitrc
      stat: path=~/.xinitrc
      register: xinitrc_presence
    - name: fail if ~/.xinitrc not created
      fail: msg="~/.xinitrc was not created by stow"
      when: xinitrc_presence.stat.exists == false
    - name: Create ~/.fonts directory
      file: path=~/.fonts state=directory
    - name: Download powerline font
      get_url: url=https://github.com/powerline/fonts/raw/master/UbuntuMono/Ubuntu%20Mono%20derivative%20Powerline.ttf
        dest=~/.fonts/
    - name: Download Source Sans Pro
      get_url: url=https://github.com/adobe-fonts/source-sans-pro/raw/release/TTF/SourceSansPro-Regular.ttf
        dest=~/.fonts/
    - name: Refresh font cache
      shell: fc-cache -f
