---
- hosts: localhost
  tasks:
    - name: Install gnu-stow
      become: yes
      apt: pkg=stow
    - name: Install dotfiles
      shell: stow {{ item }} --target=$HOME/ --dir=$HOME/.dotfiles
      with_items:
        - alacritty
        - bin
        - davfs2
        - fonts
        - git
        - gtk
        - gnupg
        - i3wm
        - ncmpcpp
        - notify
        - mpd
        - redshift
        - ruby
        - screen
        - tmux
        - vim
        - x
        - zsh
    - name: check for ~/.xinitrc
      stat: path=~/.xinitrc
      register: xinitrc_presence
    - name: fail if ~/.xinitrc not created
      fail: msg="~/.xinitrc was not created by stow"
      when: xinitrc_presence.stat.exists == false
    - name: Create ~/.fonts directory
      file: path=~/.fonts state=directory
    - name: Download Source Code Pro font
      get_url: url=https://github.com/adobe-fonts/source-code-pro/releases/download/variable-fonts/SourceCodeVariable-Roman.ttf?raw=true
        dest=~/.fonts/
    - name: Refresh font cache
      shell: fc-cache -f
