---
- hosts: localhost
  tasks:
    - name: Download rcm
      get_url: url=https://thoughtbot.github.io/rcm/debs/rcm_1.2.2-2_all.deb
        dest=/tmp/rcm.deb
    - name: Install rcm
      apt: deb=/tmp/rcm.deb
    - name: Pull submodules
      shell: git submodule foreach git pull origin master
    - name: Install dotfiles
      shell: rcup -x README.md -x screenshots chdir=~
    - name: Download powerline font
      get_url: url=https://github.com/powerline/fonts/raw/master/UbuntuMono/Ubuntu%20Mono%20derivative%20Powerline.ttf
        dest=~/.fonts/
    - name: Refresh font cache
      shell: fc-cache -f
