---
- hosts: localhost
  tasks:
    - name: Install gnu-stow
      apt: pkg=stow
    - name: Install dotfiles
      shell: stow {{ item }} --target=$HOME/ --dir=$HOME/.dotfiles
      with_items:
        - bin
        - davfs2
        - fonts
        - git
        - htop
        - i3wm
        - mutt
        - notify
        - qutebrowser
        - redshift
        - ruby
        - screen
        - shutter
        - tmux
        - urxvt
        - vim
        - x
        - zsh
    - name: Create ~/.fonts directory
      file: path=~/.fonts state=directory
    - name: Download powerline font
      get_url: url=https://github.com/powerline/fonts/raw/master/UbuntuMono/Ubuntu%20Mono%20derivative%20Powerline.ttf
        dest=~/.fonts/
    - name: Refresh font cache
      shell: fc-cache -f
