---
- hosts: localhost
  vars:
    hub_platform: linux-amd64
  tasks:
    - name: Get latest release URL
      shell: "curl -s https://api.github.com/repos/github/hub/releases/latest | jq -r '.assets[] | select(.name | test(\"{{ hub_platform }}\")) | .browser_download_url'"
      register: download_url
    - name: Download latest release
      unarchive:
        src: "{{ download_url.stdout }}"
        dest: /tmp/
        remote_src: true
    - name: Cleanup existing
      file:
        path: /tmp/hub
        state: absent
    - name: Rename unarchived folder
      shell: mv `ls -d -1 /tmp/hub*` /tmp/hub
    - name: Install latest release
      copy:
        src: /tmp/hub/bin/hub
        dest: ~/.bin/hub
        mode: 0775
