---
- hosts: localhost
  tasks:
    - name: Download package
      shell: >
        /usr/lib/apt/apt-helper download-file
        http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb
        /tmp/keyring.deb SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416
    - name: Install keyring.deb
      become: yes
      apt: deb=/tmp/keyring.deb
    - name: Add apt source
      become: yes
      apt_repository: repo="deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
    - name: Install i3
      become: yes
      apt: update_cache=yes pkg=i3
    - name: Link .xinitrc and .xsessionrc
      file: state=link src=~/.xinitrc path=~/.xsessionrc
