---
- hosts: localhost
  tasks:
    - name: Download package
      shell: /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2018.01.30_all.deb /tmp/keyring.deb SHA256:baa43dbbd7232ea2b5444cae238d53bebb9d34601cc000e82f11111b1889078a
    - name: Install keyring.deb
      become: yes
      apt: deb=/tmp/keyring.deb
    - name: Add apt source
      become: yes
      apt_repository: repo="deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
    - name: Install i3
      become: yes
      apt: update_cache=yes pkg=i3
    - name: Link .xinitrc and .xsessionrc
      file: state=link src=~/.xinitrc path=~/.xsessionrc

