---
- name: Monitoring
  hosts: localhost
  tasks:
    - name: Add check_ip script
      become: true
      ansible.builtin.copy:
        # NOTE: I don't really like that the script is in the `playbooks`
        # directory. Ideally, this copy task would be its own role with more
        # checks.
        src: ./check_ip.sh
        dest: /usr/local/bin/check_ip
        mode: a+x

    # 1. Have check scripts that put stuff into syslog
    # 2. Have a user-space cron check (anacron?) to check the syslog for
    # check_ entries
    - name: Setup check_ip cron for RaspberryPI
      ansible.builtin.cron:
        name: Check RaspberryPI connection
        minute: "*/2"
        job: /usr/local/bin/check_ip raspberrypi.local 2>&1 | /usr/bin/logger -t check_ip
        user: phansch
