---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Install Prerequisites
      apt: name={{ item }}
      with_items:
        - python3-pyqt5
        - python3-pyqt5.qtwebkit
        - python-tox
        - python3-sip
        - python3-dev
        - asciidoc
        - source-highlight
    - name: Clone repo
      git: repo=git@github.com:phansch/qutebrowser.git
        dest=~/code/qutebrowser
    - name: Generate help
      shell: phyton3 scripts/asciidoc2html.py
        chdir=~/code/qutebrowser
    - name: Install venv with tox
      shell: tox -e mkvenv
        chdir=~/code/qutebrowser
    # The wrapper script for qutebrowser is already at
    # .bin/qutebrowser
