---
- hosts: localhost
  become: yes
  become_method: sudo
  vars:
    rofi_version: 0.15.12
  tasks:
    - name: Install rofi dependencies
      apt: name={{ item }}
      with_items:
        - libxinerama-dev
        - libghc-pango-dev
        - libstartup-notification0-dev
    - name: Create tmp download dir
      file: path=/tmp/rofi state=directory
    - name: Download and unzip rofi source
      unarchive: src=https://github.com/DaveDavenport/rofi/releases/download/{{ rofi_version }}/rofi-{{ rofi_version }}.tar.gz copy=no
        dest=/tmp/rofi
    - name: Configure rofi
      shell: ./configure --prefix=/home/{{ ansible_user_id}}/.local/ chdir=/tmp/rofi/rofi-{{ rofi_version }}
    - name: Make rofi
      shell: make chdir=/tmp/rofi/rofi-{{ rofi_version }}
    - name: Make install rofi
      shell: make install chdir=/tmp/rofi/rofi-{{ rofi_version }}



