---
# Various things to automate my streaming/video conf setup
- name: Streaming setup
  hosts: localhost
  become: true
  tasks:
    - name: Install obs
      ansible.builtin.apt:
        pkg:
          - obs-studio
          - v4l2loopback-dkms

    # Used to forward audio from obs to other programs.
    # This way, noise filters can be applied to the audio input in OBS
    - name: Add a virtual sink output to pulseaudio
      ansible.builtin.lineinfile:
        path: /etc/pulse/default.pa
        line: load-module module-null-sink sink_name=Virtual_Sink sink_properties=device.description=Virtual_Sink
