---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure udev directory
      file: path=/etc/udev/rules.d state=directory
    - name: Copy udev rules for touchpad
      template:
        src=../templates/udev/01-touchpad.rules.j2
        dest=/etc/udev/rules.d/01-touchpad.rules
        owner=root
        group=root
      register: udevrules
    - name: Reload udev rules
      shell: udevadm trigger
      when: udevrules.changed

