---
- name: Download package  # noqa 305
  shell: >
    /usr/lib/apt/apt-helper download-file
    https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2020.02.03_all.deb
    /tmp/keyring.deb SHA256:c5dd35231930e3c8d6a9d9539c846023fe1a08e4b073ef0d2833acd815d80d48
  changed_when: false
- name: Install keyring.deb
  apt: deb=/tmp/keyring.deb
- name: Add apt source
  apt_repository: repo="deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
- name: Install i3
  apt: update_cache=yes pkg=i3
- name: Check if ~/.xinitrc exists
  stat:
    path: ~/.xinitrc
  register: xinitrc_file
- name: Link .xinitrc and .xsessionrc
  file: state=link src=~/.xinitrc path=~/.xsessionrc
  when: xinitrc_file.stat.exists
