---
- name: Download package # noqa command-instead-of-shell
  ansible.builtin.shell: >
    /usr/lib/apt/apt-helper download-file
    https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb
    /tmp/keyring.deb SHA256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734
  changed_when: false
- name: Install keyring.deb
  ansible.builtin.apt:
    deb: /tmp/keyring.deb
- name: Add apt source
  ansible.builtin.apt_repository:
    repo: "deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
    state: present
- name: Install i3
  ansible.builtin.apt:
    update_cache: "yes"
    pkg: i3
- name: Check if ~/.xinitrc exists
  ansible.builtin.stat:
    path: ~/.xinitrc
  register: xinitrc_file
- name: Link .xinitrc and .xsessionrc
  ansible.builtin.file:
    state: link
    src: ~/.xinitrc
    path: ~/.xsessionrc
  when: xinitrc_file.stat.exists
