---
- name: Ensure shared-mime-info is installed
  apt:
    pkg:
      - shared-mime-info
- name: Prepare markdown mimetype directory
  file:
    path: ~/.local/share/mime/packages/
    state: directory
    recurse: true
- name: Create new markdown mimetype file
  copy:
    content: ""
    dest: ~/.local/share/mime/packages/text-markdown.xml
    force: false
- name: Insert content into mimetype file
  copy: content={{ mime_content }} dest=~/.local/share/mime/packages/text-markdown.xml
  notify: Update mime database
