#!/usr/bin/env ruby

msg = `git log -1 --pretty=format:%s`
dir = `git rev-parse --show-toplevel`
project = File.basename(dir)
branch = `git branch`

msg.strip!
project.strip!
branch.strip!

­­`jou -a "New commit: /#{msg}/ on branch [#{branch}] for #{project}"`