---
markdown_mimetype_mime_content: |
  <?xml version="1.0"?>
  <mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
    <mime-type type="text/plain">
      <glob pattern="*.md"/>
      <glob pattern="*.mkd"/>
      <glob pattern="*.markdown"/>
    </mime-type>
  </mime-info>
