---
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Every Friday at 14:00 UTC
    - cron: '0 14 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lints:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          docker build -t dotfiles .

      - name: Test
        run: |
          docker run dotfiles /bin/bash -c "./test/vim && ./test/shellcheck"

      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  full-setup-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          docker build -t dotfiles .

      - name: Test
        run: |
          # shellcheck disable=SC1091
          docker run dotfiles /bin/bash -c "./setup -a && ./test/i3"

      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
