theme = "slick"
icons = "awesome"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
use_nag = true
nag_path = "i3-nagbar"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d.%m, %R"
