icons_format = "{icon}"

[theme]
theme = "plain"

[icons]
icons = "awesome4"

[[block]]
block = "pomodoro"
message = "Take a break!"
break_message = "Back to work!"
notify_cmd = "notify-send '{msg}'"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d.%m, %R') "
