icons_format = "{icon}"

[theme]
theme = "slick"

[icons]
icons = "awesome6"

[[block]]
block = "pomodoro"
message = "Take a break!"
break_message = "Back to work!"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d.%m, %R') "
